export type OrderData = {
    fees: any[];
    items: {
      key: string;
      id: number;
      type: string;
      quantity: number;
      quantity_limits: any;
      name: string;
      short_description: string;
      description: string;
      sku: string;
      low_stock_remaining: null | number;
      backorders_allowed: boolean;
      show_backorder_badge: boolean;
      sold_individually: boolean;
      permalink: string;
      images: any[];
      variation: any[];
      item_data: any[];
      prices: any;
      totals: any;
      catalog_visibility: string;
      extensions: any;
    }[];
    totals: {
      total_tax: string;
      tax_lines: any[];
      total_fees: string;
      total_items: string;
      total_price: string;
      currency_code: string;
      total_fees_tax: string;
      total_discount: string;
      total_shipping: string;
      total_items_tax: string;
      currency_symbol: string;
      currency_prefix: string;
      currency_suffix: string;
      total_discount_tax: string;
      total_shipping_tax: string;
      currency_minor_unit: number;
      currency_decimal_separator: string;
      currency_thousand_separator: string;
    };
    errors: any[];
    coupons: any[];
    extensions: any;
    items_count: number;
    cross_sells: any[];
    items_weight: number;
    needs_payment: boolean;
    needs_shipping: boolean;
    shipping_rates: {
      package_id: number;
      name: string;
      destination: any;
      items: any[];
      shipping_rates: any[];
    }[];
    billing_address: {
      city: string;
      state: string;
      email: string;
      phone: string;
      company: string;
      country:
    | 'AL'
    | 'AD'
    | 'AT'
    | 'BY'
    | 'BE'
    | 'BA'
    | 'BG'
    | 'HR'
    | 'CY'
    | 'CZ'
    | 'DK'
    | 'EE'
    | 'FI'
    | 'FR'
    | 'DE'
    | 'GR'
    | 'HU'
    | 'IS'
    | 'IE'
    | 'IT'
    | 'XK'
    | 'LV'
    | 'LI'
    | 'LT'
    | 'LU'
    | 'MT'
    | 'MD'
    | 'MC'
    | 'ME'
    | 'NL'
    | 'MK'
    | 'NO'
    | 'PL'
    | 'PT'
    | 'RO'
    | 'RU'
    | 'SM'
    | 'RS'
    | 'SK'
    | 'SI'
    | 'ES'
    | 'SE'
    | 'CH'
    | 'UA'
    | 'GB'
    | 'VA';
      postcode: string;
      last_name: string;
      address_1: string;
      address_2: string;
      first_name: string;
    };
    payment_methods: string;
    shipping_address: {
      city: string;
      state: string;
      phone: string;
      company: string;
      country:
      | 'AL'
      | 'AD'
      | 'AT'
      | 'BY'
      | 'BE'
      | 'BA'
      | 'BG'
      | 'HR'
      | 'CY'
      | 'CZ'
      | 'DK'
      | 'EE'
      | 'FI'
      | 'FR'
      | 'DE'
      | 'GR'
      | 'HU'
      | 'IS'
      | 'IE'
      | 'IT'
      | 'XK'
      | 'LV'
      | 'LI'
      | 'LT'
      | 'LU'
      | 'MT'
      | 'MD'
      | 'MC'
      | 'ME'
      | 'NL'
      | 'MK'
      | 'NO'
      | 'PL'
      | 'PT'
      | 'RO'
      | 'RU'
      | 'SM'
      | 'RS'
      | 'SK'
      | 'SI'
      | 'ES'
      | 'SE'
      | 'CH'
      | 'UA'
      | 'GB'
      | 'VA';
      postcode: string;
      last_name: string;
      address_1: string;
      address_2: string;
      first_name: string;
    };
    payment_requirements: string[];
    has_calculated_shipping: boolean;
    customer_note: string;
    nonce: string;
    cartToken: string;
  };